# Statically link the MSVC C runtime so the bridge runs on machines
# without the Visual C++ Redistributable installed (e.g. clean Win10).
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
